FROM node:20-alpine
WORKDIR /app

COPY package*.json ./

COPY . .

ENV NODE_ENV=development
ENV VITE_API_BASE_URL=http://localhost:3000
ENV VITE_H3_RESOLUTION=8
ENV CHOKIDAR_USEPOLLING=true

CMD ["sh", "-c", "npm install && npm run dev -- --host 0.0.0.0 --port 5173"]
